#ifndef KERNEL_ECALL_H
#define KERNEL_ECALL_H

#include <stdint.h>

typedef enum : uint64_t {
    ECALL_SYSTEM_RESET = 0x00,
    ECALL_CONSOLE_INPUT,
    ECALL_CONSOLE_OUTPUT,
    ECALL_AUXILIARY_INPUT,
    ECALL_AUXILIARY_OUTPUT,
    ECALL_LIST_OUTPUT,
    ECALL_DIRECT_CONSOLE_IO,
    ECALL_AUXILIARY_INPUT_STATUS,
    ECALL_AUXILIARY_OUTPUT_STATUS,
    ECALL_PRINT_STRING,
    ECALL_READ_CONSOLE_BUFFER,
    ECALL_GET_CONSOLE_STATUS,
    ECALL_GET_SET_SYSTEM_CONTROL_BLOCK_PARAMETER = 0x31,
    ECALL_GET_SET_PROGRAM_RETURN_CODE = 0x6c,
    ECALL_GET_SET_CONSOLE_MODE,
    ECALL_GET_SET_OUTPUT_DELIMITER,
    ECALL_PRINT_BLOCK,
    ECALL_LIST_BLOCK,
} SysCallNumber;


void kernel_ecall(uint64_t a_regs[8]);


#endif //KERNEL_ECALL_H
