#ifndef KERNEL_SYSCALL_H
#define KERNEL_SYSCALL_H

#include <stdint.h>

typedef enum : uint64_t {
    SYSCALL_SYSTEM_RESET = 0x00,
    SYSCALL_CONSOLE_INPUT,
    SYSCALL_CONSOLE_OUTPUT,
    SYSCALL_AUXILIARY_INPUT,
    SYSCALL_AUXILIARY_OUTPUT,
    SYSCALL_LIST_OUTPUT,
    SYSCALL_DIRECT_CONSOLE_IO,
    SYSCALL_AUXILIARY_INPUT_STATUS,
    SYSCALL_AUXILIARY_OUTPUT_STATUS,
    SYSCALL_PRINT_STRING,
    SYSCALL_READ_CONSOLE_BUFFER,
    SYSCALL_GET_CONSOLE_STATUS,
    SYSCALL_GET_SET_PROGRAM_RETURN_CODE = 0x6c,
    SYSCALL_GET_SET_CONSOLE_MODE,
    SYSCALL_GET_SET_OUTPUT_DELIMITER,
    SYSCALL_PRINT_BLOCK,
    SYSCALL_LIST_BLOCK,
} SysCallNumber;

[[gnu::nonnull]]
void kernel_syscall(uint64_t a_regs[8]);

#endif //KERNEL_SYSCALL_H
